apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
      app: login-app
  name: login-app
spec:
  replicas: 1
  selector:
    matchLabels:
        app: login-app
  strategy: 
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
          app: login-app
      name: login-app
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: MONGODB_URL
          value: ""
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: secretpasar
              key: secretToken
        - name: JWT_SECRET
          value: "secretpassword0101101010"
        - name: JWT_ACCESS_EXPIRATION_MINUTES
          value: 30
        - name: JWT_REFRESH_EXPIRATION_DAYS
          value: 30
        - name: JWT_RESET_PASSWORD_EXPIRATION_MINUTES
          value: 10
        - name: JWT_VERIFY_EMAIL_EXPIRATION_MINUTES
          value: 10
        image: syawqy.id/login-app
        imagePullPolicy: Always
        name: login-app
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}