apiVersion: v1
kind: Service
metadata:
  name: login-app
spec:
  selector:
    app: login-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
        - name: login-app
          image: syawqy/login-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: MONGODB_URL
              value: "mongodb://mongo:27017/dev"
            - name: JWT_SECRET
              value: "secretpassword0101101010"
            - name: JWT_ACCESS_EXPIRATION_MINUTES
              value: "30"
            - name: JWT_REFRESH_EXPIRATION_DAYS
              value: "30"
            - name: JWT_RESET_PASSWORD_EXPIRATION_MINUTES
              value: "10"
            - name: JWT_VERIFY_EMAIL_EXPIRATION_MINUTES
              value: "10"
          imagePullPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc